name: Build conda docker images

on:
  push:
    branches:
      main
    paths:
      - conda/Dockerfile
      - 'common/*'
      - .github/workflows/build-conda-images.yml
  pull_request:
    paths:
      - conda/Dockerfile
      - 'common/*'
      - .github/workflows/build-conda-images.yml

env:
  DOCKER_REGISTRY: "docker.io"
  DOCKER_BUILDKIT: 1
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  WITH_PUSH: ${{ github.event_name == 'push' }}

jobs:
  build-docker:
    runs-on: linux.2xlarge
    strategy:
      matrix:
        cuda_version: ["10.2", "11.3", "11.5", "cpu"]
    env:
      CUDA_VERSION: ${{ matrix.cuda_version }}
    steps:
      - name: Checkout PyTorch builder
        uses: actions/checkout@v2
      - name: Authenticate if WITH_PUSH
        run: |
          if [[ "${WITH_PUSH}" == true ]]; then
            echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_ID}" --password-stdin
          fi
      - name: Build Docker Image
        run: |
          conda/build_docker.sh
